package com.ems2;

import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.GraphWalker;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;
import java.time.LocalDateTime;
import java.io.IOException;
import java.time.Duration;

import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.WebElement;


import java.util.regex.Matcher;
import java.util.regex.Pattern;

import java.util.HashMap;
import java.util.*;

import org.testng.Assert;
import org.testng.annotations.AfterSuite;

import java.util.Arrays;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.UnexpectedAlertBehaviour;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;

import io.github.bonigarcia.wdm.WebDriverManager;

//import com.ems2.EMS_Login;
//import com.ems2.EMS_Admin;
//import com.ems2.EMS_Employee;

import com.ems2.EMS_Tests;

/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */

@GraphWalker(value = "quick_random(reached_vertex(v_You_have_successfully_applied_for_leave_displayed) && edge_coverage(100))", start = "e_Open_login_page", groups =  { "default" })
public class SomeSmallTest extends ExecutionContext implements EMS_Tests
{

  public static WebDriver driver;
  public static int count = 1; 

  @Override
  public void e_Open_login_page()  
  {
    System.out.println("Running: e_Open_login_page()");
    ChromeOptions chromeOptions = new ChromeOptions();
    WebDriverManager.chromedriver().setup();
    chromeOptions.setExperimentalOption("excludeSwitches",
        Arrays.asList("disable-popup-blocking", "enable-automation"));
    chromeOptions.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
    chromeOptions.addArguments("--remote-allow-origins=*");
    chromeOptions.addArguments("chrome.switches", "--disable-extensions --disable-extensions-file-access-check --disable-extensions-http-throttling --disable-infobars --enable-automation --start-maximized");
    chromeOptions.addArguments("--disable-extensions");
    chromeOptions.addArguments("test-type");
    Map<String, Object> prefs = new HashMap<String, Object>();
    prefs.put("credentials_enable_service", false);
    prefs.put("profile.password_manager_enabled", false);
    chromeOptions.setExperimentalOption("prefs", prefs);
//    chromeOptions.addArguments("--headless");
    
    driver = new ChromeDriver(chromeOptions);
    System.out.println("Browser launched...");

    driver.manage().window().maximize();
    System.out.println("Window is maximised...");
    JavascriptExecutor scrptExec = (JavascriptExecutor) driver;
    scrptExec.executeScript("Object.defineProperty(navigator, 'driver', {get: () => undefined})");
    driver.get("http://localhost:8080/");
    System.out.println("Website is launched...");
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Login_page_opened()   
  {
    System.out.println("Running: v_Login_page_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h3[contains(text(),'Login')]")).isDisplayed(),"Login page opened...");
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

/*  
  @Override
  public void e_Login_with_empty_credentials() {
    System.out.println("Running: e_Login_with_empty_credentials()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).clear();
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).clear();

    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with empty credentials...");
  }
*/  

  @Override
  public void e_Input_incorrect_username()  
  {
    System.out.println("Running: e_Input_incorrect_username()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).sendKeys("75");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).sendKeys("password1");
    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with incorrect username...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Incorrect_username()  
  {
    System.out.println("Running: v_Incorrect_username()");
    Assert.assertTrue(driver.findElement(By.xpath("//div[contains(text(),'Bad credentials')]")).isDisplayed(),"Bad credentials message displayed...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Input_valid_username()  
  {
    System.out.println("Running: e_Input_valid_username()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).sendKeys("76");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).sendKeys("password1");
    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with valid username...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Input_nonAdmin_credentials()  
  {
    System.out.println("Running: e_Input_nonAdmin_credentials()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).sendKeys("123");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).sendKeys("password5");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }


//driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
//System.out.println("Sign In button clicked with valid username...");

  @Override
  public void e_Click_sign_in_button()  
  {
    System.out.println("Running: e_Click_sign_in_button()");
    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with NonAdmin username...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_NonAdmin_details_entered()  
  {
    System.out.println("Running: v_NonAdmin_details_entered()");
    String usernameEntered = driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).getAttribute("value");
    Assert.assertTrue(usernameEntered.equalsIgnoreCase("123"),"Non-admin details filled...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Admin_logged_in()  
  {
    System.out.println("Running: v_Admin_logged_in()");
    Assert.assertTrue(driver.findElement(By.xpath("//a[contains(text(),'Logout')]")).isDisplayed(),"Logged in successfully...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Logout()  
  {
    System.out.println("Running: e_Logout()");
    if(count<5)
    {
    	driver.findElement(By.xpath("//a[contains(text(),'Logout')]")).click();
        count++;
    	System.out.println("Logout button clicked...");
    	driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
    }
    if(count>=5)
    {
    	driver.quit();
    }
  }

  @Override
  public void v_NonAdmin_logged_in()  
  {
    System.out.println("Running: v_NonAdmin_logged_in()");
    String empID = driver.findElement(By.xpath("//tbody/tr[2]/td[1]")).getText();
    Assert.assertTrue(empID.equalsIgnoreCase("123"),"Non-admin employee logged in...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_NonAdmin_Logout()  
  {
    System.out.println("Running: e_NonAdmin_Logout()");
    driver.findElement(By.xpath("//a[contains(text(),'Logout')]")).click();
    System.out.println("Logout button clicked...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Input_incorrect_password()  
  {
    System.out.println("Running: e_Input_incorrect_password()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).sendKeys("76");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).sendKeys("password123");
    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with incorrect password...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Incorrect_password()  
  {
    System.out.println("Running: v_Incorrect_password()");
    String id = driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).getAttribute("value");
    String pwd = driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).getAttribute("value");
    Assert.assertTrue(id.equalsIgnoreCase("")&&pwd.equalsIgnoreCase(""),"Fields are emptied...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Input_valid_password()  
  {
    System.out.println("Running: e_Input_valid_password()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).sendKeys("76");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).sendKeys("password1");
    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with valid password...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Login_with_valid_credentials()  
  {
    System.out.println("Running: e_Login_with_valid_credentials()");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]")).sendKeys("76");
    driver.findElement(By.xpath("//body[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]")).sendKeys("password1");
    driver.findElement(By.xpath("//body/div[1]/div[2]/div[1]/form[1]/input[1]")).click();
    System.out.println("Sign In button clicked with valid credentials...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }



//ADMIN FUNCTIONALITIES...
/*  
  @Override
  public void e_Check_ADMIN_checkbox_and_click_register() {
    System.out.println("Running: e_Check_ADMIN_checkbox_and_click_register()");
      //driver.findElement(By.xpath("//input[@id='roles1']")).click();
      //driver.findElement(By.id("roles1")).click();
    //WebElement checkbox = driver.findElement(By.className("m-2"));
    //checkbox.click();
    //Actions action = new Actions(driver);
    //action.moveToElement(checkbox).click().build().perform();
    JavascriptExecutor execu = (JavascriptExecutor) driver;
    execu.executeScript("document.getElementsByClassName('m-2').click();");

//    //body[1]/div[1]/form[1]/div[1]/div[20]/div[1]/input[1]
//    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();    

    JavascriptExecutor executr = (JavascriptExecutor) driver;
    executr.executeScript("document.getElementsByClassName(\"btn-primary\").click();");

    //driver.findElement(By.className("btn-primary")).click();

  }
  
  @Override
  public void v_Update_employee_form_opened() {
    System.out.println("Running: v_Update_employee_form_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Update employee id:76')]")).isDisplayed(),"Update employee form opened...");
  }
*/
  @Override
  public void v_Leave_details_page_opened()  
  {
    System.out.println("Running: v_Leave_details_page_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Leave Details')]")).isDisplayed(),"Leave details page opened...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_View_employee_attendance_clicked()  
  {
    System.out.println("Running: e_View_employee_attendance_clicked()");
    driver.findElement(By.xpath("//a[contains(text(),'View Employee Attendance')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Add_leave_details_page_opened()  
  {
    System.out.println("Running: v_Add_leave_details_page_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Enter leave Details')]")).isDisplayed(),"Enter Leave details page opened...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

//    //input[@id='earnedLeave']
//    //input[@id='covidLeave']  
//    //input[@id='inicidentalLeave']
//    //input[@id='leaveWithoutPay']
//    //input[@id='shortLeave']
//    //body/div[1]/form[1]/div[1]/div[6]/input[1]

//    //th[contains(text(),'Earned Leave')]
//    //th[contains(text(),'Covid Leave')]
//    //th[contains(text(),'Incidental Leave')]
//    //th[contains(text(),'Leave without pay')]
//    //th[contains(text(),'short leave')]

/*
  @Override
  public void e_Set_leaves_for_all_employees_again() {
    System.out.println("Running: v_Add_leave_details_page_opened()");
    driver.findElement(By.xpath("//button[contains(text(),'Set Leaves for All Employees')]")).click();
  }  
*/
//    e_Set_leaves_for_all_employees_again



  @Override
  public void v_Form_filled()  
  {
    System.out.println("Running: v_Form_filled()");
    Assert.assertFalse(driver.findElement(By.xpath("//input[@id='shortLeave']")).getAttribute("value").equalsIgnoreCase("0"),"Form filled...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Fill_form()  
  {
    System.out.println("Running: e_Fill_form()");
    driver.findElement(By.xpath("//input[@id='earnedLeave']")).clear();
    driver.findElement(By.xpath("//input[@id='earnedLeave']")).sendKeys("10");

    driver.findElement(By.xpath("//input[@id='covidLeave']")).clear();
    driver.findElement(By.xpath("//input[@id='covidLeave']")).sendKeys("9");

    driver.findElement(By.xpath("//input[@id='inicidentalLeave']")).clear();
    driver.findElement(By.xpath("//input[@id='inicidentalLeave']")).sendKeys("8");

    driver.findElement(By.xpath("//input[@id='leaveWithoutPay']")).clear();
    driver.findElement(By.xpath("//input[@id='leaveWithoutPay']")).sendKeys("7");

    driver.findElement(By.xpath("//input[@id='shortLeave']")).clear();
    driver.findElement(By.xpath("//input[@id='shortLeave']")).sendKeys("6");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Submit_button_clicked()  
  {
    System.out.println("Running: e_Submit_button_clicked()");
    driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[6]/input[1]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }


/*  @Override
  public void v_Add_new_employee_form() {
    System.out.println("Running: v_Add_new_employee_form()");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Add new Employee')]")).isDisplayed(),"Add new employee form opened...");
  }

  @Override
  public void e_Update_button_next_to_empID_76_clicked() {
    System.out.println("Running: e_Update_button_next_to_empID_76_clicked()");
    driver.findElement(By.xpath("//body[1]/div[1]/table[1]/tbody[1]/tr[2]/td[10]/a[1]")).click();
  }

  @Override
  public void v_NonAdmin_Employee_added() {
    System.out.println("Running: v_NonAdmin_Employee_added()");
    Assert.assertTrue(driver.findElement(By.xpath("//a[contains(text(),'Logout')]")).isDisplayed(),"Admin employee added...");
  }

  @Override
  public void v_EmpID_76_salary_updated() {
    System.out.println("Running: v_EmpID_76_salary_updated()");
    Assert.assertTrue(driver.findElement(By.xpath("//td[contains(text(),'55000.0')]")).isDisplayed(),"Employee salary updated...");

  }

  @Override
  public void e_Back_to_home_page() {
    System.out.println("Running: e_Back_to_home_page()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }

  @Override
  public void v_Admin_employee_added() {
    System.out.println("Running: v_Admin_emloyee_added()");
    //driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[21]/input[1]")).click();
    //driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
    Assert.assertTrue(driver.findElement(By.xpath("//a[contains(text(),'Logout')]")).isDisplayed(),"Admin employee added...");
  }

  @Override
  public void e_Navigate_back_to_Admin_page_again() {
    System.out.println("Running: e_Navigate_back_to_Admin_page_again()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }

  @Override
  public void e_Navigate_back_to_user_logged_in_page() {
    System.out.println("Running: e_Navigate_back_to_user_logged_in_page()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }*/

/*
  @Override
  public void e_Go_back_to_user_logged_in_page() {
    System.out.println("Running: e_Go_back_to_user_logged_in_page()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }
*/

  @Override
  public void e_Click_on_Attendance_from_personal_details_page()  
  {
    System.out.println("Running: e_Click_on_Attendance_from_personal_details_page()");
    driver.findElement(By.xpath("//body[1]/nav[1]/div[1]/div[1]/ul[1]/li[3]/a[1]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }  

/*  @Override
  public void v_Form_filled_with_valid_data() {
    System.out.println("Running: v_Form_filled_with_valid_data()");
    Assert.assertTrue(!driver.findElement(By.xpath("//input[@id='infoToColleaguePhone']")).getAttribute("value").isEmpty(),"Form filled...");
  }*/

  @Override
  public void v_All_attendance_page_opened()  
  {
    System.out.println("Running: v_All_attendance_page_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//th[contains(text(),'Attendance Category')]")).isDisplayed(),"All attendance page opened...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Navigate_back_to_Admin_page()  
  {
    System.out.println("Running: e_Navigate_back_to_Admin_page()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

/*  @Override
  public void e_Fill_form_with_valid_data() {
    System.out.println("Running: e_Fill_form_with_valid_data()");
*/    
/*
//input[@id='firstName']
//input[@id='lastName']
//input[@id='salary']
//input[@id='email']
//input[@id='password']
//input[@id='phoneNo']
//input[@id='gender']
//input[@id='departmentName']
//input[@id='address']
//input[@id='birthDate']
//input[@id='nationality']
//input[@id='adharNo']
//input[@id='passportNo']
//input[@id='panNo']
//input[@id='bloodGroup']
//input[@id='infoToRelativeName']
//input[@id='infoToRelativePhoneNo']
//input[@id='infoToColleagueName']
//input[@id='infoToColleaguePhone']

//input[@id='roles1']

//body/div[1]/form[1]/div[1]/div[21]/input[1]

*/    
/*    driver.findElement(By.xpath("//input[@id='firstName']")).sendKeys("Dave");
    driver.findElement(By.xpath("//input[@id='lastName']")).sendKeys("Smith");
    driver.findElement(By.xpath("//input[@id='salary']")).sendKeys("40000");
    driver.findElement(By.xpath("//input[@id='email']")).sendKeys("email123@example.com");
    driver.findElement(By.xpath("//input[@id='password']")).sendKeys("password76543");
    driver.findElement(By.xpath("//input[@id='phoneNo']")).sendKeys("500-899-1234");
    driver.findElement(By.xpath("//input[@id='gender']")).sendKeys("Male");
    driver.findElement(By.xpath("//input[@id='departmentName']")).sendKeys("IT");
    driver.findElement(By.xpath("//input[@id='address']")).sendKeys("123 Green Boulavard");
    driver.findElement(By.xpath("//input[@id='birthDate']")).sendKeys("1988-08-04");
    driver.findElement(By.xpath("//input[@id='nationality']")).sendKeys("Italian");
    driver.findElement(By.xpath("//input[@id='adharNo']")).sendKeys("876512344321");
    driver.findElement(By.xpath("//input[@id='passportNo']")).sendKeys("H321456789");
    driver.findElement(By.xpath("//input[@id='panNo']")).sendKeys("PQ345678321D");
    driver.findElement(By.xpath("//input[@id='bloodGroup']")).sendKeys("A+");
    driver.findElement(By.xpath("//input[@id='infoToRelativeName']")).sendKeys("John");
    driver.findElement(By.xpath("//input[@id='infoToRelativePhoneNo']")).sendKeys("543-123-5678");
    driver.findElement(By.xpath("//input[@id='infoToColleagueName']")).sendKeys("Judy");
    driver.findElement(By.xpath("//input[@id='infoToColleaguePhone']")).sendKeys("544-789-1234");
    //driver.findElement(By.xpath("//input[@id='roles1']")).click();

    //driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }

  @Override
  public void e_Uncheck_ADMIN_checkbox_and_click_register() {
    System.out.println("Running: e_Uncheck_ADMIN_checkbox_and_click_register()");
    JavascriptExecutor execut = (JavascriptExecutor) driver;
    execut.executeScript("document.getElementsByClassName("+"btn-primary"+").click();");
    //driver.findElement(By.className("btn-primary")).click();
  }

  @Override
  public void e_Salary_changed_and_register_button_clicked() {
    System.out.println("Running: e_Salary_changed_and_register_button_clicked()");
    driver.findElement(By.xpath("//input[@id='salary']")).clear();
    driver.findElement(By.xpath("//input[@id='salary']")).sendKeys("75000");
    //driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[21]/input[1]")).click();    
    //driver.findElement(By.xpath("//input[@id='password']")).clear();
    driver.findElement(By.xpath("//input[@id='password']")).sendKeys("password1");
    driver.findElement(By.className("btn-primary")).click();
    //      //body[1]/div[1]/form[1]/div[1]/div[21]/input[1]

    //driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }*/

/*
  @Override
  public void User_logged_in() {
    System.out.println("Running: v_User_logged_in()");
  }
*/  

  @Override
  public void e_Add_leave_details_clicked()  
  {
    System.out.println("Running: e_Add_leave_details_clicked()");
    driver.findElement(By.xpath("//a[contains(text(),'Add Leave Details')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
    
  }

/*  @Override
  public void e_Create_new_employee_button_clicked() {
    System.out.println("Running: e_Create_new_employee_button_clicked()");
    driver.findElement(By.xpath("//a[contains(text(),'Create New Employee')]")).click();
  }*/

  @Override
  public void e_View_leave_details_clicked()  
  {
    System.out.println("Running: e_View_leave_details_clicked()");
    driver.findElement(By.xpath("//a[contains(text(),'View Leave Details')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Leaves_set_for_all_employees()  
  {
    System.out.println("Running: v_Leaves_set_for_all_employees()");
    Assert.assertTrue(driver.findElement(By.xpath("//div[contains(text(),'Leave For Employees set successfully')]")).isDisplayed(),"Leaves set successfully...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Set_leaves_for_all_employees()  
  {
    System.out.println("Running: e_Set_leaves_for_all_employees()");
    driver.findElement(By.xpath("//button[contains(text(),'Set Leaves for All Employees')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_Employee_Self_Service_Management()  
  {
    System.out.println("Running: e_Click_on_Employee_Self_Service_Management()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Pending_leaves_displayed()  
  {
    System.out.println("Running: v_Pending_leaves_displayed()");
    Assert.assertTrue(driver.findElement(By.xpath("//th[contains(text(),'No of Days leave is requested')]")).isDisplayed(),"Pending leaves displayed...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_View_pending_leaves()  
  {
    System.out.println("Running: e_Click_on_View_pending_leaves()");
    driver.findElement(By.xpath("//button[contains(text(),'View Pending Leaves')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

//    //button[contains(text(),'Approve')]

//    http://localhost:8080/employees/leave/allleaves?message=Leave+Approved

  @Override
  public void v_Leave_approved_URL()  
  {
    System.out.println("Running: e_Click_on_View_pending_leaves()");
    Assert.assertTrue(driver.getCurrentUrl().contains("Leave+Approved"),"Leave Approved...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_Approve_button()  
  {
    System.out.println("Running: e_Click_on_Approve_button()");
    driver.findElement(By.xpath("//button[contains(text(),'Approve')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

//    //a[contains(text(),'Manage Employees')]

  @Override
  public void e_Click_on_manage_employees()  
  {
    System.out.println("Running: e_Click_on_manage_employees()");
    driver.findElement(By.xpath("//a[contains(text(),'Manage Employees')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }



//EMPLOYEE LEAVES...
  @Override
  public void v_You_did_not_enter_leave_in_correct_format_displayed()  
  {
    System.out.println("Running: v_You_did_not_enter_leave_in_correct_format_displayed()");
//      //div[contains(text(),'You did not enter the leave in correct format!Plea')]
    Assert.assertTrue(driver.findElement(By.xpath("//div[contains(text(),'You did not enter the leave in correct format!Plea')]")).isDisplayed(),"Leave date format incorrect...");

     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void v_You_have_successfully_applied_for_leave_displayed()  
  {
    System.out.println("Running: v_You_have_successfully_applied_for_leave_displayed()");
    Assert.assertTrue(driver.findElement(By.xpath("//div[contains(text(),'You have succesfully applied for leave!')]")).isDisplayed(),"Successfully applied leave...");

     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void e_Click_on_view_personal_details()  
  {
    System.out.println("Running: e_Click_on_view_personal_details()");
    driver.findElement(By.xpath("//a[contains(text(),'View Personal Details')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Earned_leave_selected()  
  {
    System.out.println("Running: v_Earned_leave_selected()");
    Select se = new Select(driver.findElement(By.xpath("//select[@id='leaveCategory']")));
    WebElement firstSelectedOption = se.getFirstSelectedOption();
    Assert.assertTrue(firstSelectedOption.getText().contains("Earned"),"Earned leave selected...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Number_of_days_populated()  
  {
    System.out.println("Running: v_Number_of_days_populated()");
    String days = driver.findElement(By.xpath("//input[@id='noOfDays']")).getAttribute("value");
    Assert.assertTrue(days.equalsIgnoreCase("1"),"Valid number of days entered...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Number_of_days_populated_again()  
  {
    System.out.println("Running: v_Number_of_days_populated_again()");    
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Earned_leave_selected_again()  
  {
    System.out.println("Running: v_Earned_leave_selected_again()");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void e_Enter_Reason_for_leave_again()  
  {
    System.out.println("Running: e_Enter_Reason_for_leave_again()");

    driver.findElement(By.xpath("//input[@id='LeaveReason']")).sendKeys("Illness");    
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_view_leave_details()  
  {
    System.out.println("Running: e_Click_on_view_leave_details()");
    driver.findElement(By.xpath("//a[contains(text(),'View Leave Details')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Apply_leave_form_opened()  
  {
    System.out.println("Running: v_Apply_leave_form_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h2[contains(text(),'Enter Details To Apply for Leave')]")).isDisplayed(),"Apply Leave form opened...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Enter_invalid_date_format()  
  {
    System.out.println("Running: e_Enter_invalid_date_format()");
    driver.findElement(By.xpath("//input[@id='fromDate']")).sendKeys("2023-28-08");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void e_Register_button_clicked_with_invalid_Start_date()  
  {
    System.out.println("Running: e_Register_button_clicked_with_invalid_Start_date()");
    String startDate = driver.findElement(By.xpath("//input[@id='fromDate']")).getAttribute("value");
    if(startDate.matches("\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])"))
    {
      //driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[5]/input[1]")).click();
      String date = "valid";
    }
    if(!startDate.matches("\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])"))
    {
      //driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[5]/input[1]")).click();
      String date = "invalid";
      driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[5]/input[1]")).click();    
    }
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void v_Personal_details_displayed()  
  {
    System.out.println("Running: v_Personal_details_displayed()");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Personal Details')]")).isDisplayed(),"Personal details displayed...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Valid_Leave_start_date_populated()  
  {
    System.out.println("Running: v_Valid_Leave_start_date_populated()");
    String startDate = driver.findElement(By.xpath("//input[@id='fromDate']")).getAttribute("value");
    //Assert.assertTrue(startDate.matches("\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])"),"Valid date format...");
    Assert.assertTrue(startDate.equalsIgnoreCase(java.time.LocalDate.now().toString()),"Valid date format...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Select_Earned_leave_for_Leave_category()  
  {
    System.out.println("Running: e_Select_Earned_leave_for_Leave_category()");
    Select se = new Select(driver.findElement(By.xpath("//select[@id='leaveCategory']")));
    se.selectByValue("Earned Leave");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Invalid_Leave_start_date_populated()  
  {
    System.out.println("Running: v_Invalid_Leave_start_date_populated()");
    String startDate = driver.findElement(By.xpath("//input[@id='fromDate']")).getAttribute("value");
    //Assert.assertFalse(startDate.matches("\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])"),"Invalid date format...");
    Assert.assertTrue(startDate.equalsIgnoreCase("2023-28-08"),"Invalid date format...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_view_leave_details_again()  
  {
    System.out.println("Running: e_Click_on_view_leave_details_again()");
    driver.findElement(By.xpath("//a[contains(text(),'View Leave Details')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void e_Enter_Reason_for_leave()  
  {
    System.out.println("Running: e_Enter_Reason_for_leave()");
    driver.findElement(By.xpath("//input[@id='LeaveReason']")).sendKeys("Illness");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Reason_for_leave_entered()  
  {
    System.out.println("Running: v_Reason_for_leave_entered()");
    Assert.assertFalse(driver.findElement(By.xpath("//input[@id='LeaveReason']")).getAttribute("value").isEmpty(),"Reason for leave entered...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Enter_valid_Number_of_days_again()  
  {
    System.out.println("Running: e_Enter_valid_Number_of_days_again()");
    driver.findElement(By.xpath("//input[@id='noOfDays']")).clear();
    driver.findElement(By.xpath("//input[@id='noOfDays']")).sendKeys("1");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Enter_valid_Number_of_days()  
  {
    System.out.println("Running: e_Enter_valid_Number_of_days()");
    driver.findElement(By.xpath("//input[@id='noOfDays']")).clear();
    driver.findElement(By.xpath("//input[@id='noOfDays']")).sendKeys("1");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
    
  }

  @Override
  public void e_Enter_valid_date_format()  
  {
    System.out.println("Running: e_Enter_valid_date_format()");
    driver.findElement(By.xpath("//input[@id='fromDate']")).sendKeys(java.time.LocalDate.now().toString());
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_Apply_for_leave_button()  
  {
    System.out.println("Running: e_Click_on_Apply_for_leave_button()");
    driver.findElement(By.xpath("//button[contains(text(),'Apply For Leave')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

/*
  @Override
  public void User_logged_in() {
    System.out.println("Running: v_User_logged_in()");
  }
*/  

  @Override
  public void v_Employee_leave_details_displayed()  
  {
    System.out.println("Running: v_Employee_leave_details_displayed()");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Employee Leave Details')]")).isDisplayed(),"Employee leave details displayed...");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Register_button_clicked_with_valid_Start_date()  
  {
    System.out.println("Running: e_Register_button_clicked_with_valid_Start_date()");
    String startDate = driver.findElement(By.xpath("//input[@id='fromDate']")).getAttribute("value");
    if(startDate.matches("\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])"))
    {
      //driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[5]/input[1]")).click();
      String date = "valid";
      driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[5]/input[1]")).click();      
    }
    if(!startDate.matches("\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])"))
    {
      //driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[5]/input[1]")).click();
      String date = "invalid";
    }
    //driver.navigate().back();
    //driver.findElement(By.xpath("//button[contains(text(),'Apply For Leave')]")).click();

     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

//      //div[contains(text(),"You don't have sufficient leave in this category")]
  }

  @Override
  public void v_Reason_for_leave_entered_again()  
  {
    System.out.println("Running: v_Reason_for_leave_entered_again()");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));

  }

  @Override
  public void e_Select_Earned_leave_for_Leave_category_again()  
  {
    System.out.println("Running: v_Reason_for_leave_entered_again()");
    Select se = new Select(driver.findElement(By.xpath("//select[@id='leaveCategory']")));
    se.selectByValue("Earned Leave");
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Attendance_page_opened()  
  {
    System.out.println("Running: v_Attendance_page_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h2[contains(text(),'Enter Details To Mark Attendance')]")).isDisplayed(),"Attendance page opened...");
        //    //h2[contains(text(),'Enter Details To Mark Attendance')]
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_Attendance()  
  {
    System.out.println("Running: e_Click_on_Attendance()");
    driver.findElement(By.xpath("//body[1]/nav[1]/div[1]/div[1]/ul[1]/li[3]/a[1]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_Submit()  
  {
    System.out.println("Running: e_Click_Submit()");
    driver.findElement(By.xpath("//body/div[1]/form[1]/div[1]/div[2]/input[1]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Submit_attendance()  
  {
    System.out.println("Running: v_Submit_attendance()");
    //Assert.assertTrue(driver.findElement(By.xpath("//div[contains(text(),'You have succesfully Marked your Attendance!')]")).isDisplayed(),"Attendance submitted...");
    Assert.assertTrue(driver.findElement(By.xpath("//h1[contains(text(),'Employee Details')]")).isDisplayed());
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

/*
  @Override
  public void e_Click_on_View_Employee_Attendance() {
    System.out.println("Running: e_Click_on_View_Employee_Attendance()");
    driver.findElement(By.xpath("//a[contains(text(),'View Employee Attendance')]")).click();
  }

  @Override
  public void v_All_Attendance_opened() {
    System.out.println("Running: e_Click_on_View_Employee_Attendance()");
    Assert.assertTrue(driver.findElement(By.xpath("//th[contains(text(),'Sign In')]")).isDisplayed(),"All Attendance viewed...");
  }


  @Override
  public void e_Traverse_back_to_Home_page() {
    System.out.println("Running: e_Traverse_back_to_Home_page()");
    //driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }


  @Override
  public void e_Traverse_back_to_Logged_in_page() {
    System.out.println("Running: e_Traverse_back_to_Logged_in_page()");
    driver.findElement(By.xpath("//a[contains(text(),'Employee Self Service Management')]")).click();
  }
*/

  @Override
  public void e_Click_on_Attendance_again()  
  {
    System.out.println("Running: e_Click_on_Attendance_again()");  
    driver.findElement(By.xpath("//body[1]/nav[1]/div[1]/div[1]/ul[1]/li[3]/a[1]")).click();    
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void v_Attendance_Status_page_opened()  
  {
    System.out.println("Running: v_Attendance_Status_page_opened()");
    Assert.assertTrue(driver.findElement(By.xpath("//h2[contains(text(),'Attendance Status')]")).isDisplayed());
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_Attendance_Status()  
  {
    System.out.println("Running: v_Attendance_Status_page_opened()");
    driver.findElement(By.xpath("//a[contains(text(),'Attendance Status')]")).click();
     driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Override
  public void e_Click_on_Back_to_Employee_Details() 
  {
    System.out.println("Running: e_Click_on_Back_to_Employee_Details()");
    driver.findElement(By.xpath("//button[contains(text(),'Back to Employee Details')]")).click();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @AfterSuite
  public void QuitBrowser()  throws InterruptedException, IOException {
    Thread.sleep(5000);
    System.out.println("Quitting the Browser now...");
    driver.quit();
  }

}
